### ISSUE TITLE
Scrutinizer: still any use for PHP?

### ISSUE THREAD

**Issue by mindplay-dk** [auraphp/Aura.Router#200]
Hey,

I noticed you're one of the few people still using Scrutinizer - and as with all of my own projects, nothing appears to work anymore.

None of my projects using Scrutinizer have worked in years - whenever I work on one of my PHP projects, I try again to see if I can get it working, and today I actually got one of my projects to pass an inspection, using the following bit of config:

```yaml
checks:
    php: true
build:
    image: default-bionic
    environment:
        php: 8.1.28
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
```

The magic is in `build.image` - it looks like their *default* default image doesn't even work for PHP, so you have to change this to `default-bionic`, and the `environment.php` setting should be set to an [official PHP release](https://github.com/php/php-src/tags) tag.

I honestly don't know if the rest of these settings actually do something, or if so what - their documentation is an absolute mess, and their basic PHP instructions have not worked in at least 5 years.

And when I say this "works", I mean it actually ran an inspection and flagged it green - but it doesn't look like the values on the badges were actually updated, and the [main page](https://scrutinizer-ci.com/g/mindplay-dk/sql/?branch=master) for that project *still* shows inspections from 5 years ago.

So yeah, maybe this bit of configuration helps you get your build working again - I figured it might be helpful.

But also, I was wondering, what is your impression or experience with Scrutinizer in recent years? To me, it's starting to look a lot like abandonware, at least with regards to their PHP support? Literally nothing works by default and the documentation is barely there.

I'm wondering if I should switch to something like [coveralls](https://coveralls.io/) for the code coverage badge, and just forget about the code quality rating. I don't think there's another code quality product (that's free for open source) that even supports PHP?

What do you think? 🤔
